---

-
  hosts : AppServer

  vars_files :
     - example11_vars.yml


  tasks : 
    - name : Test Dictionary Key value
      debug :
        msg : result is {{ example_key }}

    - name : Test Dictionary Key value
      debug :
        msg : result is {{ dict }}
    
    - name : Test Dictionary Key value with dot notation
      debug :
        msg : result is {{ inline_dict.dict_key }}


    - name : Test named list Key value
      debug :
        msg : result is {{ named_list }}
    
    - name : Test namedlist Key value with dot notation
      debug :
        msg : result is {{ named_list.3 }}

    - name : Test named list Key value with python notation
      debug :
        msg : result is {{ inline_named_list[4] }}
...