---
# try with AppServer as hosts
-
  hosts : all
  gather_facts : true

  tasks :
    - name : Test Host vars
      debug :
        msg : "{{ hostvars[ansible_hostname].ansible_port }}"
    
    - name : Test Host vars dict notation
      debug :
        msg : "{{ hostvars[ansible_hostname]['ansible_port'] }}"

...
    