---

-
  hosts : AppServer
  user : ansibleadm
  gather_facts : true

  vars :
    motd_centos : "Example data only for Centos machines"
    motd_ubuntu : "Example data only for Ubuntu machines"

  tasks :
  - name : Configure a motd - centos
    copy :
      content : "{{ motd_centos }}"
      dest : /etc/motd
    when : ansible_distribution == "CentOS"
  
  - name : Configure a motd - ubuntu
    copy :
      content : "{{ motd_ubuntu }}"
      dest : /etc/motd
    when : ansible_distribution == "Ubuntu"

...

    