---

-
  hosts : AppServer
  user : ansibleadm
  gather_facts : false 

  vars : 
    motd : "Example data from yaml file \n"


  tasks : 
  - name : Configure a motd
    copy : 
      content : "{{ motd }}"
      dest : /etc/motd
...
