---

-
  hosts : AppServer

  vars : 
    dict : 
      dict_key : dictionary  value

  tasks : 
    - name : Test Dictionary Key value
      debug :
        msg : result is {{ dict }}
    
    - name : Test Dictionary Key value with dot notation
      debug :
        msg : result is {{ dict.dict_key }}

    - name : Test Dictionary Key value with python notation
      debug :
        msg : result is {{ dict['dict_key'] }}