---

- 
  hosts : AppServer
  user : ansibleadm
  gather_facts : true

  vars :
    motd_centos : "Example data only for Centos machines"
    motd_ubuntu : "Example data only for Ubuntu machines"
  
  tasks :
  - name : Configure a motd - centos
    copy : 
      content : "{{ motd_centos }}"
      dest : /etc/motd
    notify : MOTD Changed
    when : ansible_distribution == "CentOS"

  - name : Configure a motd - Ubuntu
    copy : 
      content : "{{ motd_ubuntu }}"
      dest : /etc/motd
    notify : MOTD Changed 
    when : ansible_distribution == "Ubuntu"

  handlers :
    - name : MOTD Changed
      debug : 
        msg : The MOTD has been changed

...
